//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppProductores.WebServicesProductores {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseAgroContract", Namespace="http://schemas.datacontract.org/2004/07/AgroMarketRD.Service.Contracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppProductores.WebServicesProductores.ProductResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppProductores.WebServicesProductores.ProductUnitResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppProductores.WebServicesProductores.GeneralResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppProductores.WebServicesProductores.OfferResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppProductores.WebServicesProductores.IntentionBuyingResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppProductores.WebServicesProductores.IntentionsSellResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppProductores.WebServicesProductores.SellsResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppProductores.WebServicesProductores.LoginResponse))]
    public partial class BaseAgroContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AppProductores.WebServicesProductores.ErrorResponse ErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AppProductores.WebServicesProductores.ErrorResponse Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorResponse", Namespace="http://schemas.datacontract.org/2004/07/AgroMarketRD.Service.Contracts")]
    [System.SerializableAttribute()]
    public partial class ErrorResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductResponse", Namespace="http://schemas.datacontract.org/2004/07/AgroMarketRD.Service.Contracts")]
    [System.SerializableAttribute()]
    public partial class ProductResponse : AppProductores.WebServicesProductores.BaseAgroContract {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AppProductores.WebServicesProductores.Product[] ProductsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AppProductores.WebServicesProductores.Product[] Products {
            get {
                return this.ProductsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductsField, value) != true)) {
                    this.ProductsField = value;
                    this.RaisePropertyChanged("Products");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductUnitResponse", Namespace="http://schemas.datacontract.org/2004/07/AgroMarketRD.Service.Contracts")]
    [System.SerializableAttribute()]
    public partial class ProductUnitResponse : AppProductores.WebServicesProductores.BaseAgroContract {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AppProductores.WebServicesProductores.ProductUnit[] UnitTypesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AppProductores.WebServicesProductores.ProductUnit[] UnitTypes {
            get {
                return this.UnitTypesField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitTypesField, value) != true)) {
                    this.UnitTypesField = value;
                    this.RaisePropertyChanged("UnitTypes");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GeneralResponse", Namespace="http://schemas.datacontract.org/2004/07/AgroMarketRD.Service.Contracts")]
    [System.SerializableAttribute()]
    public partial class GeneralResponse : AppProductores.WebServicesProductores.BaseAgroContract {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OfferResponse", Namespace="http://schemas.datacontract.org/2004/07/AgroMarketRD.Service.Contracts")]
    [System.SerializableAttribute()]
    public partial class OfferResponse : AppProductores.WebServicesProductores.BaseAgroContract {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AppProductores.WebServicesProductores.Offer[] OffersField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AppProductores.WebServicesProductores.Offer[] Offers {
            get {
                return this.OffersField;
            }
            set {
                if ((object.ReferenceEquals(this.OffersField, value) != true)) {
                    this.OffersField = value;
                    this.RaisePropertyChanged("Offers");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IntentionBuyingResponse", Namespace="http://schemas.datacontract.org/2004/07/AgroMarketRD.Service.Contracts")]
    [System.SerializableAttribute()]
    public partial class IntentionBuyingResponse : AppProductores.WebServicesProductores.BaseAgroContract {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AppProductores.WebServicesProductores.IntentionBuying[] IntentionsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AppProductores.WebServicesProductores.IntentionBuying[] Intentions {
            get {
                return this.IntentionsField;
            }
            set {
                if ((object.ReferenceEquals(this.IntentionsField, value) != true)) {
                    this.IntentionsField = value;
                    this.RaisePropertyChanged("Intentions");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IntentionsSellResponse", Namespace="http://schemas.datacontract.org/2004/07/AgroMarketRD.Service.Contracts")]
    [System.SerializableAttribute()]
    public partial class IntentionsSellResponse : AppProductores.WebServicesProductores.BaseAgroContract {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AppProductores.WebServicesProductores.IntentionSell[] IntentionsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AppProductores.WebServicesProductores.IntentionSell[] Intentions {
            get {
                return this.IntentionsField;
            }
            set {
                if ((object.ReferenceEquals(this.IntentionsField, value) != true)) {
                    this.IntentionsField = value;
                    this.RaisePropertyChanged("Intentions");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SellsResponse", Namespace="http://schemas.datacontract.org/2004/07/AgroMarketRD.Service.Contracts")]
    [System.SerializableAttribute()]
    public partial class SellsResponse : AppProductores.WebServicesProductores.BaseAgroContract {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AppProductores.WebServicesProductores.Sell[] SellListField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AppProductores.WebServicesProductores.Sell[] SellList {
            get {
                return this.SellListField;
            }
            set {
                if ((object.ReferenceEquals(this.SellListField, value) != true)) {
                    this.SellListField = value;
                    this.RaisePropertyChanged("SellList");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginResponse", Namespace="http://schemas.datacontract.org/2004/07/AgroMarketRD.Service.Contracts")]
    [System.SerializableAttribute()]
    public partial class LoginResponse : AppProductores.WebServicesProductores.BaseAgroContract {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/AgroMarketRD.Service.Contracts")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductUnit", Namespace="http://schemas.datacontract.org/2004/07/AgroMarketRD.Service.Contracts")]
    [System.SerializableAttribute()]
    public partial class ProductUnit : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Offer", Namespace="http://schemas.datacontract.org/2004/07/AgroMarketRD.Service.Contracts")]
    [System.SerializableAttribute()]
    public partial class Offer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceUnitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductUnitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductUnitIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PriceUnit {
            get {
                return this.PriceUnitField;
            }
            set {
                if ((this.PriceUnitField.Equals(value) != true)) {
                    this.PriceUnitField = value;
                    this.RaisePropertyChanged("PriceUnit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductCode {
            get {
                return this.ProductCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductCodeField, value) != true)) {
                    this.ProductCodeField = value;
                    this.RaisePropertyChanged("ProductCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName {
            get {
                return this.ProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNameField, value) != true)) {
                    this.ProductNameField = value;
                    this.RaisePropertyChanged("ProductName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductUnit {
            get {
                return this.ProductUnitField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductUnitField, value) != true)) {
                    this.ProductUnitField = value;
                    this.RaisePropertyChanged("ProductUnit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductUnitId {
            get {
                return this.ProductUnitIdField;
            }
            set {
                if ((this.ProductUnitIdField.Equals(value) != true)) {
                    this.ProductUnitIdField = value;
                    this.RaisePropertyChanged("ProductUnitId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Productor {
            get {
                return this.ProductorField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductorField, value) != true)) {
                    this.ProductorField = value;
                    this.RaisePropertyChanged("Productor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductorId {
            get {
                return this.ProductorIdField;
            }
            set {
                if ((this.ProductorIdField.Equals(value) != true)) {
                    this.ProductorIdField = value;
                    this.RaisePropertyChanged("ProductorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IntentionBuying", Namespace="http://schemas.datacontract.org/2004/07/AgroMarketRD.Service.Contracts")]
    [System.SerializableAttribute()]
    public partial class IntentionBuying : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuyerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BuyerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateCreationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ExpirationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] IntentionsToSellIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AppProductores.WebServicesProductores.ProductIntention[] ProductListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Buyer {
            get {
                return this.BuyerField;
            }
            set {
                if ((object.ReferenceEquals(this.BuyerField, value) != true)) {
                    this.BuyerField = value;
                    this.RaisePropertyChanged("Buyer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BuyerId {
            get {
                return this.BuyerIdField;
            }
            set {
                if ((this.BuyerIdField.Equals(value) != true)) {
                    this.BuyerIdField = value;
                    this.RaisePropertyChanged("BuyerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateCreation {
            get {
                return this.DateCreationField;
            }
            set {
                if ((this.DateCreationField.Equals(value) != true)) {
                    this.DateCreationField = value;
                    this.RaisePropertyChanged("DateCreation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ExpirationDate {
            get {
                return this.ExpirationDateField;
            }
            set {
                if ((this.ExpirationDateField.Equals(value) != true)) {
                    this.ExpirationDateField = value;
                    this.RaisePropertyChanged("ExpirationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] IntentionsToSellId {
            get {
                return this.IntentionsToSellIdField;
            }
            set {
                if ((object.ReferenceEquals(this.IntentionsToSellIdField, value) != true)) {
                    this.IntentionsToSellIdField = value;
                    this.RaisePropertyChanged("IntentionsToSellId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AppProductores.WebServicesProductores.ProductIntention[] ProductList {
            get {
                return this.ProductListField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductListField, value) != true)) {
                    this.ProductListField = value;
                    this.RaisePropertyChanged("ProductList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductIntention", Namespace="http://schemas.datacontract.org/2004/07/AgroMarketRD.Service.Contracts")]
    [System.SerializableAttribute()]
    public partial class ProductIntention : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceUnitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductUnitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductUnitIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal QuantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PriceUnit {
            get {
                return this.PriceUnitField;
            }
            set {
                if ((this.PriceUnitField.Equals(value) != true)) {
                    this.PriceUnitField = value;
                    this.RaisePropertyChanged("PriceUnit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductCode {
            get {
                return this.ProductCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductCodeField, value) != true)) {
                    this.ProductCodeField = value;
                    this.RaisePropertyChanged("ProductCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName {
            get {
                return this.ProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNameField, value) != true)) {
                    this.ProductNameField = value;
                    this.RaisePropertyChanged("ProductName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductUnit {
            get {
                return this.ProductUnitField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductUnitField, value) != true)) {
                    this.ProductUnitField = value;
                    this.RaisePropertyChanged("ProductUnit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductUnitId {
            get {
                return this.ProductUnitIdField;
            }
            set {
                if ((this.ProductUnitIdField.Equals(value) != true)) {
                    this.ProductUnitIdField = value;
                    this.RaisePropertyChanged("ProductUnitId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IntentionSell", Namespace="http://schemas.datacontract.org/2004/07/AgroMarketRD.Service.Contracts")]
    [System.SerializableAttribute()]
    public partial class IntentionSell : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateCreationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AppProductores.WebServicesProductores.ProductIntention[] ProductListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SellerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SellerIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateCreation {
            get {
                return this.DateCreationField;
            }
            set {
                if ((this.DateCreationField.Equals(value) != true)) {
                    this.DateCreationField = value;
                    this.RaisePropertyChanged("DateCreation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AppProductores.WebServicesProductores.ProductIntention[] ProductList {
            get {
                return this.ProductListField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductListField, value) != true)) {
                    this.ProductListField = value;
                    this.RaisePropertyChanged("ProductList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Seller {
            get {
                return this.SellerField;
            }
            set {
                if ((object.ReferenceEquals(this.SellerField, value) != true)) {
                    this.SellerField = value;
                    this.RaisePropertyChanged("Seller");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SellerId {
            get {
                return this.SellerIdField;
            }
            set {
                if ((this.SellerIdField.Equals(value) != true)) {
                    this.SellerIdField = value;
                    this.RaisePropertyChanged("SellerId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sell", Namespace="http://schemas.datacontract.org/2004/07/AgroMarketRD.Service.Contracts")]
    [System.SerializableAttribute()]
    public partial class Sell : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuyerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BuyerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IntentionBuyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IntentionSellIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AppProductores.WebServicesProductores.ProductIntention[] ProductListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SellerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SellerIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Buyer {
            get {
                return this.BuyerField;
            }
            set {
                if ((object.ReferenceEquals(this.BuyerField, value) != true)) {
                    this.BuyerField = value;
                    this.RaisePropertyChanged("Buyer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BuyerId {
            get {
                return this.BuyerIdField;
            }
            set {
                if ((this.BuyerIdField.Equals(value) != true)) {
                    this.BuyerIdField = value;
                    this.RaisePropertyChanged("BuyerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreationDate {
            get {
                return this.CreationDateField;
            }
            set {
                if ((this.CreationDateField.Equals(value) != true)) {
                    this.CreationDateField = value;
                    this.RaisePropertyChanged("CreationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IntentionBuyId {
            get {
                return this.IntentionBuyIdField;
            }
            set {
                if ((this.IntentionBuyIdField.Equals(value) != true)) {
                    this.IntentionBuyIdField = value;
                    this.RaisePropertyChanged("IntentionBuyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IntentionSellId {
            get {
                return this.IntentionSellIdField;
            }
            set {
                if ((this.IntentionSellIdField.Equals(value) != true)) {
                    this.IntentionSellIdField = value;
                    this.RaisePropertyChanged("IntentionSellId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AppProductores.WebServicesProductores.ProductIntention[] ProductList {
            get {
                return this.ProductListField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductListField, value) != true)) {
                    this.ProductListField = value;
                    this.RaisePropertyChanged("ProductList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Seller {
            get {
                return this.SellerField;
            }
            set {
                if ((object.ReferenceEquals(this.SellerField, value) != true)) {
                    this.SellerField = value;
                    this.RaisePropertyChanged("Seller");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SellerId {
            get {
                return this.SellerIdField;
            }
            set {
                if ((this.SellerIdField.Equals(value) != true)) {
                    this.SellerIdField = value;
                    this.RaisePropertyChanged("SellerId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseRequest", Namespace="http://schemas.datacontract.org/2004/07/AgroMarketRD.Service.Requests")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppProductores.WebServicesProductores.IntentionToBuyFromOffers))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppProductores.WebServicesProductores.IntentionToSellRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppProductores.WebServicesProductores.IntentionToBuyFromProducts))]
    public partial class BaseRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                if ((object.ReferenceEquals(this.tokenField, value) != true)) {
                    this.tokenField = value;
                    this.RaisePropertyChanged("token");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                if ((object.ReferenceEquals(this.userNameField, value) != true)) {
                    this.userNameField = value;
                    this.RaisePropertyChanged("userName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IntentionToBuyFromOffers", Namespace="http://schemas.datacontract.org/2004/07/AgroMarketRD.Service.Requests")]
    [System.SerializableAttribute()]
    public partial class IntentionToBuyFromOffers : AppProductores.WebServicesProductores.BaseRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] OffersIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] OffersId {
            get {
                return this.OffersIdField;
            }
            set {
                if ((object.ReferenceEquals(this.OffersIdField, value) != true)) {
                    this.OffersIdField = value;
                    this.RaisePropertyChanged("OffersId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IntentionToSellRequest", Namespace="http://schemas.datacontract.org/2004/07/AgroMarketRD.Service.Requests")]
    [System.SerializableAttribute()]
    public partial class IntentionToSellRequest : AppProductores.WebServicesProductores.BaseRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IntentionToBuydIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AppProductores.WebServicesProductores.InnerProductRequest[] ProductListField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IntentionToBuydId {
            get {
                return this.IntentionToBuydIdField;
            }
            set {
                if ((this.IntentionToBuydIdField.Equals(value) != true)) {
                    this.IntentionToBuydIdField = value;
                    this.RaisePropertyChanged("IntentionToBuydId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AppProductores.WebServicesProductores.InnerProductRequest[] ProductList {
            get {
                return this.ProductListField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductListField, value) != true)) {
                    this.ProductListField = value;
                    this.RaisePropertyChanged("ProductList");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IntentionToBuyFromProducts", Namespace="http://schemas.datacontract.org/2004/07/AgroMarketRD.Service.Requests")]
    [System.SerializableAttribute()]
    public partial class IntentionToBuyFromProducts : AppProductores.WebServicesProductores.BaseRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AppProductores.WebServicesProductores.InnerProductRequest[] ProductListField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AppProductores.WebServicesProductores.InnerProductRequest[] ProductList {
            get {
                return this.ProductListField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductListField, value) != true)) {
                    this.ProductListField = value;
                    this.RaisePropertyChanged("ProductList");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InnerProductRequest", Namespace="http://schemas.datacontract.org/2004/07/AgroMarketRD.Service.Requests")]
    [System.SerializableAttribute()]
    public partial class InnerProductRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceUnitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductUnitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PriceUnit {
            get {
                return this.PriceUnitField;
            }
            set {
                if ((this.PriceUnitField.Equals(value) != true)) {
                    this.PriceUnitField = value;
                    this.RaisePropertyChanged("PriceUnit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductCode {
            get {
                return this.ProductCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductCodeField, value) != true)) {
                    this.ProductCodeField = value;
                    this.RaisePropertyChanged("ProductCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductUnit {
            get {
                return this.ProductUnitField;
            }
            set {
                if ((this.ProductUnitField.Equals(value) != true)) {
                    this.ProductUnitField = value;
                    this.RaisePropertyChanged("ProductUnit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebServicesProductores.IAgroMarketService")]
    public interface IAgroMarketService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/SignIn", ReplyAction="http://tempuri.org/IAgroMarketService/SignInResponse")]
        AppProductores.WebServicesProductores.LoginResponse SignIn(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/SignIn", ReplyAction="http://tempuri.org/IAgroMarketService/SignInResponse")]
        System.Threading.Tasks.Task<AppProductores.WebServicesProductores.LoginResponse> SignInAsync(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/LogOff", ReplyAction="http://tempuri.org/IAgroMarketService/LogOffResponse")]
        AppProductores.WebServicesProductores.ErrorResponse LogOff(string userName, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/LogOff", ReplyAction="http://tempuri.org/IAgroMarketService/LogOffResponse")]
        System.Threading.Tasks.Task<AppProductores.WebServicesProductores.ErrorResponse> LogOffAsync(string userName, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/GetProducts", ReplyAction="http://tempuri.org/IAgroMarketService/GetProductsResponse")]
        AppProductores.WebServicesProductores.ProductResponse GetProducts(string userName, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/GetProducts", ReplyAction="http://tempuri.org/IAgroMarketService/GetProductsResponse")]
        System.Threading.Tasks.Task<AppProductores.WebServicesProductores.ProductResponse> GetProductsAsync(string userName, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/GetUnitTypes", ReplyAction="http://tempuri.org/IAgroMarketService/GetUnitTypesResponse")]
        AppProductores.WebServicesProductores.ProductUnitResponse GetUnitTypes(string userName, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/GetUnitTypes", ReplyAction="http://tempuri.org/IAgroMarketService/GetUnitTypesResponse")]
        System.Threading.Tasks.Task<AppProductores.WebServicesProductores.ProductUnitResponse> GetUnitTypesAsync(string userName, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/CreateOffer", ReplyAction="http://tempuri.org/IAgroMarketService/CreateOfferResponse")]
        AppProductores.WebServicesProductores.GeneralResponse CreateOffer(string userName, string token, int cantidad, int tipoUnidad, decimal precioUnidad, string codigoProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/CreateOffer", ReplyAction="http://tempuri.org/IAgroMarketService/CreateOfferResponse")]
        System.Threading.Tasks.Task<AppProductores.WebServicesProductores.GeneralResponse> CreateOfferAsync(string userName, string token, int cantidad, int tipoUnidad, decimal precioUnidad, string codigoProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/RemoveOffer", ReplyAction="http://tempuri.org/IAgroMarketService/RemoveOfferResponse")]
        AppProductores.WebServicesProductores.ErrorResponse RemoveOffer(string userName, string token, int offerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/RemoveOffer", ReplyAction="http://tempuri.org/IAgroMarketService/RemoveOfferResponse")]
        System.Threading.Tasks.Task<AppProductores.WebServicesProductores.ErrorResponse> RemoveOfferAsync(string userName, string token, int offerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/GetOffer", ReplyAction="http://tempuri.org/IAgroMarketService/GetOfferResponse")]
        AppProductores.WebServicesProductores.OfferResponse GetOffer(string userName, string token, int offerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/GetOffer", ReplyAction="http://tempuri.org/IAgroMarketService/GetOfferResponse")]
        System.Threading.Tasks.Task<AppProductores.WebServicesProductores.OfferResponse> GetOfferAsync(string userName, string token, int offerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/GetAllOffers", ReplyAction="http://tempuri.org/IAgroMarketService/GetAllOffersResponse")]
        AppProductores.WebServicesProductores.OfferResponse GetAllOffers(string userName, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/GetAllOffers", ReplyAction="http://tempuri.org/IAgroMarketService/GetAllOffersResponse")]
        System.Threading.Tasks.Task<AppProductores.WebServicesProductores.OfferResponse> GetAllOffersAsync(string userName, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/CreateIntentionToBuy", ReplyAction="http://tempuri.org/IAgroMarketService/CreateIntentionToBuyResponse")]
        AppProductores.WebServicesProductores.GeneralResponse CreateIntentionToBuy(AppProductores.WebServicesProductores.IntentionToBuyFromProducts request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/CreateIntentionToBuy", ReplyAction="http://tempuri.org/IAgroMarketService/CreateIntentionToBuyResponse")]
        System.Threading.Tasks.Task<AppProductores.WebServicesProductores.GeneralResponse> CreateIntentionToBuyAsync(AppProductores.WebServicesProductores.IntentionToBuyFromProducts request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/CreateIntentionToBuyFromOffers", ReplyAction="http://tempuri.org/IAgroMarketService/CreateIntentionToBuyFromOffersResponse")]
        AppProductores.WebServicesProductores.GeneralResponse CreateIntentionToBuyFromOffers(AppProductores.WebServicesProductores.IntentionToBuyFromOffers request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/CreateIntentionToBuyFromOffers", ReplyAction="http://tempuri.org/IAgroMarketService/CreateIntentionToBuyFromOffersResponse")]
        System.Threading.Tasks.Task<AppProductores.WebServicesProductores.GeneralResponse> CreateIntentionToBuyFromOffersAsync(AppProductores.WebServicesProductores.IntentionToBuyFromOffers request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/RemoveIntentionToBuy", ReplyAction="http://tempuri.org/IAgroMarketService/RemoveIntentionToBuyResponse")]
        AppProductores.WebServicesProductores.ErrorResponse RemoveIntentionToBuy(string userName, string token, int intentionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/RemoveIntentionToBuy", ReplyAction="http://tempuri.org/IAgroMarketService/RemoveIntentionToBuyResponse")]
        System.Threading.Tasks.Task<AppProductores.WebServicesProductores.ErrorResponse> RemoveIntentionToBuyAsync(string userName, string token, int intentionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/GetIntentionToBuy", ReplyAction="http://tempuri.org/IAgroMarketService/GetIntentionToBuyResponse")]
        AppProductores.WebServicesProductores.IntentionBuyingResponse GetIntentionToBuy(string userName, string token, int intentionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/GetIntentionToBuy", ReplyAction="http://tempuri.org/IAgroMarketService/GetIntentionToBuyResponse")]
        System.Threading.Tasks.Task<AppProductores.WebServicesProductores.IntentionBuyingResponse> GetIntentionToBuyAsync(string userName, string token, int intentionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/GetAllIntentionsToBuy", ReplyAction="http://tempuri.org/IAgroMarketService/GetAllIntentionsToBuyResponse")]
        AppProductores.WebServicesProductores.IntentionBuyingResponse GetAllIntentionsToBuy(string userName, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/GetAllIntentionsToBuy", ReplyAction="http://tempuri.org/IAgroMarketService/GetAllIntentionsToBuyResponse")]
        System.Threading.Tasks.Task<AppProductores.WebServicesProductores.IntentionBuyingResponse> GetAllIntentionsToBuyAsync(string userName, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/CreateIntentionToSell", ReplyAction="http://tempuri.org/IAgroMarketService/CreateIntentionToSellResponse")]
        AppProductores.WebServicesProductores.GeneralResponse CreateIntentionToSell(AppProductores.WebServicesProductores.IntentionToSellRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/CreateIntentionToSell", ReplyAction="http://tempuri.org/IAgroMarketService/CreateIntentionToSellResponse")]
        System.Threading.Tasks.Task<AppProductores.WebServicesProductores.GeneralResponse> CreateIntentionToSellAsync(AppProductores.WebServicesProductores.IntentionToSellRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/RemoveIntentionToSell", ReplyAction="http://tempuri.org/IAgroMarketService/RemoveIntentionToSellResponse")]
        AppProductores.WebServicesProductores.ErrorResponse RemoveIntentionToSell(string userName, string token, int intentionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/RemoveIntentionToSell", ReplyAction="http://tempuri.org/IAgroMarketService/RemoveIntentionToSellResponse")]
        System.Threading.Tasks.Task<AppProductores.WebServicesProductores.ErrorResponse> RemoveIntentionToSellAsync(string userName, string token, int intentionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/GetIntentionToSell", ReplyAction="http://tempuri.org/IAgroMarketService/GetIntentionToSellResponse")]
        AppProductores.WebServicesProductores.IntentionsSellResponse GetIntentionToSell(string userName, string token, int intentionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/GetIntentionToSell", ReplyAction="http://tempuri.org/IAgroMarketService/GetIntentionToSellResponse")]
        System.Threading.Tasks.Task<AppProductores.WebServicesProductores.IntentionsSellResponse> GetIntentionToSellAsync(string userName, string token, int intentionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/GetIntentionsToSell", ReplyAction="http://tempuri.org/IAgroMarketService/GetIntentionsToSellResponse")]
        AppProductores.WebServicesProductores.IntentionsSellResponse GetIntentionsToSell(string userName, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/GetIntentionsToSell", ReplyAction="http://tempuri.org/IAgroMarketService/GetIntentionsToSellResponse")]
        System.Threading.Tasks.Task<AppProductores.WebServicesProductores.IntentionsSellResponse> GetIntentionsToSellAsync(string userName, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/MakeDeal", ReplyAction="http://tempuri.org/IAgroMarketService/MakeDealResponse")]
        AppProductores.WebServicesProductores.ErrorResponse MakeDeal(string userName, string token, int intentionSellId, int intentionBuyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/MakeDeal", ReplyAction="http://tempuri.org/IAgroMarketService/MakeDealResponse")]
        System.Threading.Tasks.Task<AppProductores.WebServicesProductores.ErrorResponse> MakeDealAsync(string userName, string token, int intentionSellId, int intentionBuyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/GetAllSells", ReplyAction="http://tempuri.org/IAgroMarketService/GetAllSellsResponse")]
        AppProductores.WebServicesProductores.SellsResponse GetAllSells(string userName, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgroMarketService/GetAllSells", ReplyAction="http://tempuri.org/IAgroMarketService/GetAllSellsResponse")]
        System.Threading.Tasks.Task<AppProductores.WebServicesProductores.SellsResponse> GetAllSellsAsync(string userName, string token);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAgroMarketServiceChannel : AppProductores.WebServicesProductores.IAgroMarketService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AgroMarketServiceClient : System.ServiceModel.ClientBase<AppProductores.WebServicesProductores.IAgroMarketService>, AppProductores.WebServicesProductores.IAgroMarketService {
        
        public AgroMarketServiceClient() {
        }
        
        public AgroMarketServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AgroMarketServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AgroMarketServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AgroMarketServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AppProductores.WebServicesProductores.LoginResponse SignIn(string userName, string password) {
            return base.Channel.SignIn(userName, password);
        }
        
        public System.Threading.Tasks.Task<AppProductores.WebServicesProductores.LoginResponse> SignInAsync(string userName, string password) {
            return base.Channel.SignInAsync(userName, password);
        }
        
        public AppProductores.WebServicesProductores.ErrorResponse LogOff(string userName, string token) {
            return base.Channel.LogOff(userName, token);
        }
        
        public System.Threading.Tasks.Task<AppProductores.WebServicesProductores.ErrorResponse> LogOffAsync(string userName, string token) {
            return base.Channel.LogOffAsync(userName, token);
        }
        
        public AppProductores.WebServicesProductores.ProductResponse GetProducts(string userName, string token) {
            return base.Channel.GetProducts(userName, token);
        }
        
        public System.Threading.Tasks.Task<AppProductores.WebServicesProductores.ProductResponse> GetProductsAsync(string userName, string token) {
            return base.Channel.GetProductsAsync(userName, token);
        }
        
        public AppProductores.WebServicesProductores.ProductUnitResponse GetUnitTypes(string userName, string token) {
            return base.Channel.GetUnitTypes(userName, token);
        }
        
        public System.Threading.Tasks.Task<AppProductores.WebServicesProductores.ProductUnitResponse> GetUnitTypesAsync(string userName, string token) {
            return base.Channel.GetUnitTypesAsync(userName, token);
        }
        
        public AppProductores.WebServicesProductores.GeneralResponse CreateOffer(string userName, string token, int cantidad, int tipoUnidad, decimal precioUnidad, string codigoProducto) {
            return base.Channel.CreateOffer(userName, token, cantidad, tipoUnidad, precioUnidad, codigoProducto);
        }
        
        public System.Threading.Tasks.Task<AppProductores.WebServicesProductores.GeneralResponse> CreateOfferAsync(string userName, string token, int cantidad, int tipoUnidad, decimal precioUnidad, string codigoProducto) {
            return base.Channel.CreateOfferAsync(userName, token, cantidad, tipoUnidad, precioUnidad, codigoProducto);
        }
        
        public AppProductores.WebServicesProductores.ErrorResponse RemoveOffer(string userName, string token, int offerId) {
            return base.Channel.RemoveOffer(userName, token, offerId);
        }
        
        public System.Threading.Tasks.Task<AppProductores.WebServicesProductores.ErrorResponse> RemoveOfferAsync(string userName, string token, int offerId) {
            return base.Channel.RemoveOfferAsync(userName, token, offerId);
        }
        
        public AppProductores.WebServicesProductores.OfferResponse GetOffer(string userName, string token, int offerId) {
            return base.Channel.GetOffer(userName, token, offerId);
        }
        
        public System.Threading.Tasks.Task<AppProductores.WebServicesProductores.OfferResponse> GetOfferAsync(string userName, string token, int offerId) {
            return base.Channel.GetOfferAsync(userName, token, offerId);
        }
        
        public AppProductores.WebServicesProductores.OfferResponse GetAllOffers(string userName, string token) {
            return base.Channel.GetAllOffers(userName, token);
        }
        
        public System.Threading.Tasks.Task<AppProductores.WebServicesProductores.OfferResponse> GetAllOffersAsync(string userName, string token) {
            return base.Channel.GetAllOffersAsync(userName, token);
        }
        
        public AppProductores.WebServicesProductores.GeneralResponse CreateIntentionToBuy(AppProductores.WebServicesProductores.IntentionToBuyFromProducts request) {
            return base.Channel.CreateIntentionToBuy(request);
        }
        
        public System.Threading.Tasks.Task<AppProductores.WebServicesProductores.GeneralResponse> CreateIntentionToBuyAsync(AppProductores.WebServicesProductores.IntentionToBuyFromProducts request) {
            return base.Channel.CreateIntentionToBuyAsync(request);
        }
        
        public AppProductores.WebServicesProductores.GeneralResponse CreateIntentionToBuyFromOffers(AppProductores.WebServicesProductores.IntentionToBuyFromOffers request) {
            return base.Channel.CreateIntentionToBuyFromOffers(request);
        }
        
        public System.Threading.Tasks.Task<AppProductores.WebServicesProductores.GeneralResponse> CreateIntentionToBuyFromOffersAsync(AppProductores.WebServicesProductores.IntentionToBuyFromOffers request) {
            return base.Channel.CreateIntentionToBuyFromOffersAsync(request);
        }
        
        public AppProductores.WebServicesProductores.ErrorResponse RemoveIntentionToBuy(string userName, string token, int intentionId) {
            return base.Channel.RemoveIntentionToBuy(userName, token, intentionId);
        }
        
        public System.Threading.Tasks.Task<AppProductores.WebServicesProductores.ErrorResponse> RemoveIntentionToBuyAsync(string userName, string token, int intentionId) {
            return base.Channel.RemoveIntentionToBuyAsync(userName, token, intentionId);
        }
        
        public AppProductores.WebServicesProductores.IntentionBuyingResponse GetIntentionToBuy(string userName, string token, int intentionId) {
            return base.Channel.GetIntentionToBuy(userName, token, intentionId);
        }
        
        public System.Threading.Tasks.Task<AppProductores.WebServicesProductores.IntentionBuyingResponse> GetIntentionToBuyAsync(string userName, string token, int intentionId) {
            return base.Channel.GetIntentionToBuyAsync(userName, token, intentionId);
        }
        
        public AppProductores.WebServicesProductores.IntentionBuyingResponse GetAllIntentionsToBuy(string userName, string token) {
            return base.Channel.GetAllIntentionsToBuy(userName, token);
        }
        
        public System.Threading.Tasks.Task<AppProductores.WebServicesProductores.IntentionBuyingResponse> GetAllIntentionsToBuyAsync(string userName, string token) {
            return base.Channel.GetAllIntentionsToBuyAsync(userName, token);
        }
        
        public AppProductores.WebServicesProductores.GeneralResponse CreateIntentionToSell(AppProductores.WebServicesProductores.IntentionToSellRequest request) {
            return base.Channel.CreateIntentionToSell(request);
        }
        
        public System.Threading.Tasks.Task<AppProductores.WebServicesProductores.GeneralResponse> CreateIntentionToSellAsync(AppProductores.WebServicesProductores.IntentionToSellRequest request) {
            return base.Channel.CreateIntentionToSellAsync(request);
        }
        
        public AppProductores.WebServicesProductores.ErrorResponse RemoveIntentionToSell(string userName, string token, int intentionId) {
            return base.Channel.RemoveIntentionToSell(userName, token, intentionId);
        }
        
        public System.Threading.Tasks.Task<AppProductores.WebServicesProductores.ErrorResponse> RemoveIntentionToSellAsync(string userName, string token, int intentionId) {
            return base.Channel.RemoveIntentionToSellAsync(userName, token, intentionId);
        }
        
        public AppProductores.WebServicesProductores.IntentionsSellResponse GetIntentionToSell(string userName, string token, int intentionId) {
            return base.Channel.GetIntentionToSell(userName, token, intentionId);
        }
        
        public System.Threading.Tasks.Task<AppProductores.WebServicesProductores.IntentionsSellResponse> GetIntentionToSellAsync(string userName, string token, int intentionId) {
            return base.Channel.GetIntentionToSellAsync(userName, token, intentionId);
        }
        
        public AppProductores.WebServicesProductores.IntentionsSellResponse GetIntentionsToSell(string userName, string token) {
            return base.Channel.GetIntentionsToSell(userName, token);
        }
        
        public System.Threading.Tasks.Task<AppProductores.WebServicesProductores.IntentionsSellResponse> GetIntentionsToSellAsync(string userName, string token) {
            return base.Channel.GetIntentionsToSellAsync(userName, token);
        }
        
        public AppProductores.WebServicesProductores.ErrorResponse MakeDeal(string userName, string token, int intentionSellId, int intentionBuyId) {
            return base.Channel.MakeDeal(userName, token, intentionSellId, intentionBuyId);
        }
        
        public System.Threading.Tasks.Task<AppProductores.WebServicesProductores.ErrorResponse> MakeDealAsync(string userName, string token, int intentionSellId, int intentionBuyId) {
            return base.Channel.MakeDealAsync(userName, token, intentionSellId, intentionBuyId);
        }
        
        public AppProductores.WebServicesProductores.SellsResponse GetAllSells(string userName, string token) {
            return base.Channel.GetAllSells(userName, token);
        }
        
        public System.Threading.Tasks.Task<AppProductores.WebServicesProductores.SellsResponse> GetAllSellsAsync(string userName, string token) {
            return base.Channel.GetAllSellsAsync(userName, token);
        }

        internal object GetAllIntentionsToBuy()
        {
            throw new NotImplementedException();
        }
    }
}
